# Generated by Django 4.2.29 on 2026-03-29 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Слаг категории')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название продукта')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Слаг продукта')),
                ('desc', models.TextField(verbose_name='Описание продукта')),
                ('use_instructions', models.TextField(verbose_name='Способ применения')),
                ('composition', models.TextField(verbose_name='Состав')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена продукта')),
                ('discount', models.IntegerField(blank=0, default=0, null=True, verbose_name='Скидка')),
                ('quantity', models.IntegerField(default=1, verbose_name='Кол-во продукта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='biocyte.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ImagesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото продукта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='biocyte.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Фото продукта',
                'verbose_name_plural': 'Фото продуктов',
            },
        ),
    ]
