# Generated by Django 4.2.29 on 2026-04-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biocyte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('excerpt', models.TextField(verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Полный текст статьи')),
                ('image', models.ImageField(upload_to='blog_images/', verbose_name='Изображение')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
