# Generated by Django 4.2.29 on 2026-05-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biocyte', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+998 (__) ___-__-__', max_length=20, verbose_name='Номер телефона')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('instagram', models.URLField(blank=True, verbose_name='Ссылка Instagram')),
                ('telegram', models.URLField(blank=True, verbose_name='Ссылка Telegram')),
                ('facebook', models.URLField(blank=True, verbose_name='Ссылка Facebook')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
