# Generated by Django 4.2.29 on 2026-05-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biocyte', '0003_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+', max_length=20, verbose_name='Номер телефона'),
        ),
    ]
