# Generated by Django 4.2.29 on 2026-07-01 15:09

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('biocyte', '0004_alter_sitesettings_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(verbose_name='Полный текст статьи'),
        ),
    ]
